"""Regenerate prototype_web/shattered_jade_battle.html from its real sources.

The standalone file is a build artifact: index.html + game.js inlined, with the
fetch-based scenario loader swapped for an EMBEDDED_SCENARIOS lookup over every
scenarios/*.json. Never edit it by hand — edit the sources and rerun:

    python3 tools/build_standalone.py        (from game01_demo/)

sim/tests/test_standalone.py pins the artifact to this builder's output, so a
stale or hand-edited standalone fails the suite.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "prototype_web", "shattered_jade_battle.html")

# the fetch loader in game.js boot() — replaced verbatim in the standalone
FETCH_BLOCK = """    const res = await fetch(`scenarios/${scenId}.json`, { cache: "no-store" });
    if (!res.ok) throw new Error("HTTP " + res.status);
    scenario = await res.json();"""
EMBED_BLOCK = """    const s = EMBEDDED_SCENARIOS[scenId];
    if (!s) throw new Error("未知战役 " + scenId + "（可用：" + Object.keys(EMBEDDED_SCENARIOS).join("、") + "）");
    scenario = JSON.parse(JSON.stringify(s));"""
FETCH_ADVICE = "——请强制刷新 Cmd+Shift+R；若仍失败，告诉我这行字。"
EMBED_ADVICE = "——战役名拼写有误？此文件离线自足，无需刷新。"


def build():
    with open(os.path.join(ROOT, "prototype_web", "index.html"), encoding="utf-8") as f:
        html = f.read()
    with open(os.path.join(ROOT, "prototype_web", "game.js"), encoding="utf-8") as f:
        js = f.read()

    scen_dir = os.path.join(ROOT, "scenarios")
    scens = {}
    for name in sorted(os.listdir(scen_dir)):
        if name.endswith(".json"):
            with open(os.path.join(scen_dir, name), encoding="utf-8") as f:
                scens[name[:-5]] = json.load(f)
    # `</` must not appear inside an inline <script>
    embedded = json.dumps(scens, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")

    assert FETCH_BLOCK in js, "game.js fetch loader changed — update build_standalone.py"
    assert FETCH_ADVICE in js, "game.js loader advice changed — update build_standalone.py"
    js = js.replace(FETCH_BLOCK, EMBED_BLOCK).replace(FETCH_ADVICE, EMBED_ADVICE)

    inline = (f"<script>\n/* GENERATED by tools/build_standalone.py — do not edit; "
              f"edit index.html / game.js / scenarios/*.json and rebuild. */\n"
              f"const EMBEDDED_SCENARIOS = {embedded};\n{js}</script>")
    needle = '<script src="game.js?v=022"></script>'
    assert needle in html, "index.html script tag changed — update build_standalone.py"
    return html.replace(needle, inline)


if __name__ == "__main__":
    out = build()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {OUT} ({len(out):,} bytes)", file=sys.stderr)
