"""Cut a STABLE release: the battle prototype AND the world map, each as one
offline self-contained file.

The dev artifacts are rebuilt on every change; releases/ holds frozen,
known-good editions you can hand anyone. Gate: the full pytest suite must be
green. The version comes from the newest DESIGN.md changelog entry, stamped
into the <title> and a build comment. The two files reference each other by
their release names, so copy them into the same folder.

    python3 tools/release.py             (from game01_demo/)
    → releases/shattered_jade_full_vX.Y.html   (THE game: map + battles, one file)
    → releases/shattered_jade_vX.Y.html        (battles only) + latest.html
    → releases/shattered_jade_world_vX.Y.html  (map only)     + latest_world.html

The FULL edition is the recommended download: battles fight inside the map
page (same-origin iframe, verdict by direct callback) — no server, no port
forwarding, no cross-file links, double-click and play.
"""
import json
import os
import re
import subprocess
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from tools.build_standalone import build  # noqa: E402

WORLD_FETCH = """    const res = await fetch(`world/${worldId}.json`, { cache: "no-store" });
    if (!res.ok) throw new Error("HTTP " + res.status);
    spec = await res.json();"""
WORLD_EMBED = """    const s = EMBEDDED_WORLDS[worldId];
    if (!s) throw new Error("未知舆图 " + worldId + "（可用：" + Object.keys(EMBEDDED_WORLDS).join("、") + "）");
    spec = JSON.parse(JSON.stringify(s));"""
FETCH_ADVICE = "——请强制刷新 Cmd+Shift+R；若仍失败，告诉我这行字。"
EMBED_ADVICE = "——舆图名拼写有误？此文件离线自足，无需刷新。"


def build_world(battle_name):
    """Assemble the offline world-map edition; battles link to battle_name."""
    with open(os.path.join(ROOT, "prototype_web", "world.html"), encoding="utf-8") as f:
        html = f.read()
    with open(os.path.join(ROOT, "prototype_web", "world.js"), encoding="utf-8") as f:
        js = f.read()
    worlds = {}
    wdir = os.path.join(ROOT, "world")
    for name in sorted(os.listdir(wdir)):
        if name.endswith(".json"):
            with open(os.path.join(wdir, name), encoding="utf-8") as f:
                worlds[name[:-5]] = json.load(f)
    embedded = json.dumps(worlds, ensure_ascii=False,
                          separators=(",", ":")).replace("</", "<\\/")
    assert WORLD_FETCH in js, "world.js fetch loader changed — update release.py"
    assert FETCH_ADVICE in js, "world.js loader advice changed — update release.py"
    js = js.replace(WORLD_FETCH, WORLD_EMBED).replace(FETCH_ADVICE, EMBED_ADVICE)
    js = js.replace("index.html?scenario=", battle_name + "?scenario=")
    html = html.replace('href="index.html"', f'href="{battle_name}"')
    inline = (f"<script>\n/* GENERATED by tools/release.py — do not edit. */\n"
              f"const EMBEDDED_WORLDS = {embedded};\n{js}</script>")
    needle = '<script src="world.js?v=001"></script>'
    assert needle in html, "world.html script tag changed — update release.py"
    return html.replace(needle, inline)


def build_full(battle_html, world_html):
    """One file to rule them all: the battle edition rides inside the world
    edition as a string, fought in a same-origin srcdoc iframe."""
    payload = json.dumps(battle_html).replace("</", "<\\/")
    inject = ("<script>\n/* the battle engine rides inside — one file, no server */\n"
              f"const EMBEDDED_BATTLE = {payload};\n</script>\n<script>")
    needle = "<script>\n/* GENERATED by tools/release.py"
    assert needle in world_html, "world standalone marker changed — update release.py"
    return world_html.replace("<script>\n/* GENERATED by tools/release.py",
                              inject + "\n/* GENERATED by tools/release.py", 1)


def design_version():
    with open(os.path.join(ROOT, "DESIGN.md"), encoding="utf-8") as f:
        m = re.search(r"\*\*v(\d+\.\d+) \((\d{4}-\d{2}-\d{2})\)\*\*", f.read())
    if not m:
        raise SystemExit("no changelog version found in DESIGN.md")
    return m.group(1), m.group(2)


def main():
    r = subprocess.run([sys.executable, "-m", "pytest", "sim/tests/", "-q"],
                       cwd=ROOT, capture_output=True, text=True)
    summary = (r.stdout.strip().splitlines() or ["?"])[-1]
    if r.returncode != 0:
        raise SystemExit(f"RELEASE BLOCKED — suite not green:\n{r.stdout}{r.stderr}")

    ver, ver_date = design_version()
    html = build()
    stamp = (f"<!-- Shattered Jade STABLE v{ver} ({ver_date}) — built "
             f"{time.strftime('%Y-%m-%d %H:%M')}, {summary} -->")
    html = html.replace("<title>碎玉 · 战斗原型 — Shattered Jade battle prototype</title>",
                        f"<title>碎玉 v{ver} — Shattered Jade stable</title>\n{stamp}", 1)
    assert stamp in html, "title tag changed — update release.py"

    out_dir = os.path.join(ROOT, "releases")
    os.makedirs(out_dir, exist_ok=True)
    battle_name = f"shattered_jade_v{ver}.html"
    # the battle edition's road back to the map points at its sibling file
    html = html.replace("world.html", f"shattered_jade_world_v{ver}.html")
    out = os.path.join(out_dir, battle_name)
    for path in (out, os.path.join(out_dir, "latest.html")):
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

    world_html = build_world(battle_name)
    world_html = world_html.replace(
        "<title>", f"{stamp}\n<title>", 1) if "<title>" in world_html else world_html
    wout = os.path.join(out_dir, f"shattered_jade_world_v{ver}.html")
    for path in (wout, os.path.join(out_dir, "latest_world.html")):
        with open(path, "w", encoding="utf-8") as f:
            f.write(world_html)

    full_html = build_full(html, world_html)
    fout = os.path.join(out_dir, f"shattered_jade_full_v{ver}.html")
    for path in (fout, os.path.join(out_dir, "latest_full.html")):
        with open(path, "w", encoding="utf-8") as f:
            f.write(full_html)

    # keep releases/ tidy: only this version's trio + the latest_* pointers
    keep = {os.path.basename(p) for p in (out, wout, fout)}
    keep |= {"latest.html", "latest_world.html", "latest_full.html"}
    for name in os.listdir(out_dir):
        if name.endswith(".html") and name not in keep:
            os.remove(os.path.join(out_dir, name))
    print(f"STABLE v{ver} released ({summary}):\n  {fout}   ← the one-file game\n"
          f"  {out}\n  {wout}\n  (+ latest_full/latest/latest_world.html)")


if __name__ == "__main__":
    main()
